name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Go to x86 Directory
      run: cd library/build/x86/
    - name: x86 build
      run: ./build.sh
    - name: Go to ARM directory
      run: cd ../library/build/arm/
    - name: ARM Build
      run: ./build.sh
