name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
    - run: cd library/build/x86/
    - run: ./build.sh
    - run: cd ../library/build/arm/
    - run: ./build.sh
